export enum PrivacyLevel {
  PUBLIC = 'PUBLIC',
  TENANT_WIDE = 'TENANT_WIDE',
  DEPARTMENT_ONLY = 'DEPARTMENT_ONLY',
  TEAM_ONLY = 'TEAM_ONLY',
  INDIVIDUAL_ONLY = 'INDIVIDUAL_ONLY',
  RESTRICTED_CLEARANCE = 'RESTRICTED_CLEARANCE'
}
