export enum MemoryCategory {
  STRATEGIC = 'STRATEGIC',
  OPERATIONAL = 'OPERATIONAL',
  FINANCIAL = 'FINANCIAL',
  CUSTOMER = 'CUSTOMER',
  TECHNICAL = 'TECHNICAL',
  COMPLIANCE = 'COMPLIANCE',
  LEARNING = 'LEARNING'
}
