export enum MemoryType {
  EXECUTIVE = 'EXECUTIVE',
  CUSTOMER = 'CUSTOMER',
  ORGANIZATION = 'ORGANIZATION',
  PRODUCT = 'PRODUCT',
  FINANCIAL = 'FINANCIAL',
  MARKETING = 'MARKETING',
  OPERATIONAL = 'OPERATIONAL',
  TECHNICAL = 'TECHNICAL'
}
