export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID_AUTHORIZED = 'PAID_AUTHORIZED',
  INVENTORY_ALLOCATED = 'INVENTORY_ALLOCATED',
  IN_FULFILLMENT = 'IN_FULFILLMENT',
  PARTIALLY_SHIPPED = 'PARTIALLY_SHIPPED',
  FULLY_SHIPPED = 'FULLY_SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  FULLY_REFUNDED = 'FULLY_REFUNDED'
}

export enum FulfillmentStatus {
  UNASSIGNED = 'UNASSIGNED',
  RELEASED_TO_FLOOR = 'RELEASED_TO_FLOOR',
  PICKING = 'PICKING',
  PACKING = 'PACKING',
  STAGED_READY = 'STAGED_READY',
  SHIPPED_DISPATCHED = 'SHIPPED_DISPATCHED',
  DELIVERED = 'DELIVERED',
  PICKED_UP_BY_CUSTOMER = 'PICKED_UP_BY_CUSTOMER',
  DELIVERY_FAILED_RETURNING = 'DELIVERY_FAILED_RETURNING'
}

export enum ReturnStatus {
  REQUESTED = 'REQUESTED',
  APPROVED_PENDING_RECEIPT = 'APPROVED_PENDING_RECEIPT',
  RECEIVED_IN_TRANSIT = 'RECEIVED_IN_TRANSIT',
  INSPECTED_PASSED_RE_STOCKED = 'INSPECTED_PASSED_RE_STOCKED',
  INSPECTED_FAILED_SCRAPPED = 'INSPECTED_FAILED_SCRAPPED',
  REFUNDED_CREDITED_CLOSED = 'REFUNDED_CREDITED_CLOSED',
  REJECTED_RETURNED_TO_CUSTOMER = 'REJECTED_RETURNED_TO_CUSTOMER'
}

export enum InventoryAllocationState {
  AVAILABLE_FOR_SALE = 'AVAILABLE_FOR_SALE',
  SOFT_RESERVED_IN_CART = 'SOFT_RESERVED_IN_CART',
  HARD_ALLOCATED_TO_ORDER = 'HARD_ALLOCATED_TO_ORDER',
  PICKED_FOR_PACKING = 'PICKED_FOR_PACKING',
  DECREMENTED_SHIPPED = 'DECREMENTED_SHIPPED'
}

export interface CommerceLifecycleState {
  readonly currentOrderStatus: OrderStatus;
  readonly activeFulfillmentStatus: FulfillmentStatus;
  readonly lastModifiedAt: Date;
}
