export type RuntimeCapabilities = 
  | 'WORKFLOW_EXECUTION'
  | 'APPROVAL_CLAIM'
  | 'TASK_DISPATCH'
  | 'SCHEDULING_RECURRING'
  | 'NOTIFICATION_PUSH'
  | 'EVENTS_PUBLISH'
  | 'POLICIES_EVALUATION'
  | 'MONITORING_READ';
