import { ExecutiveMemoryContext } from './executive-memory-context.js';
import { ExecutiveMemoryRecord } from './executive-memory-record.js';
import { StrategicObservation } from '../knowledge/strategic-observation.js';
import { ExecutiveAssumption } from '../knowledge/executive-assumption.js';
import { LessonLearned } from '../knowledge/lesson-learned.js';
import { ExecutiveInsight } from '../knowledge/executive-insight.js';
import { RememberedGoal } from '../goals/remembered-goal.js';
import { ExecutiveExperience } from '../experience/executive-experience.js';
import { ExecutiveMemoryId } from '../identity/executive-memory-id.js';

export interface ExecutiveMemory {
  /**
   * Appends or records a collection of strategic observations under the executive context.
   */
  recordObservations(
    context: ExecutiveMemoryContext,
    id: ExecutiveMemoryId,
    observations: StrategicObservation[]
  ): Promise<ExecutiveMemoryRecord>;

  /**
   * Appends or records strategic assumptions under the executive context.
   */
  recordAssumptions(
    context: ExecutiveMemoryContext,
    id: ExecutiveMemoryId,
    assumptions: ExecutiveAssumption[]
  ): Promise<ExecutiveMemoryRecord>;

  /**
   * Stores lessons learned to institutionalize failures and successes.
   */
  storeLessonsLearned(
    context: ExecutiveMemoryContext,
    id: ExecutiveMemoryId,
    lessons: LessonLearned[]
  ): Promise<ExecutiveMemoryRecord>;

  /**
   * Stores strategic insights generated by an executive brain or analytical discovery.
   */
  storeStrategicInsights(
    context: ExecutiveMemoryContext,
    id: ExecutiveMemoryId,
    insights: ExecutiveInsight[]
  ): Promise<ExecutiveMemoryRecord>;

  /**
   * Tracks and stores remembered goals with current statuses or post-mortem learnings.
   */
  trackRememberedGoals(
    context: ExecutiveMemoryContext,
    id: ExecutiveMemoryId,
    goals: RememberedGoal[]
  ): Promise<ExecutiveMemoryRecord>;

  /**
   * Updates and registers executive experiences and patterns recognized.
   */
  trackExecutiveExperiences(
    context: ExecutiveMemoryContext,
    id: ExecutiveMemoryId,
    experience: ExecutiveExperience
  ): Promise<ExecutiveMemoryRecord>;
}
