export type KnowledgeCategoryCode =
  | 'BUSINESS_STRATEGY'
  | 'CUSTOMER_INSIGHT'
  | 'PRODUCT_SPECIFICATION'
  | 'ORGANIZATIONAL_STRUCTURE'
  | 'AI_MODEL_WEIGHTS_METADATA'
  | 'COMPLIANCE_STANDARDS_GOVERNANCE';
