export enum EntityCategory {
  IDENTITY = 'IDENTITY',
  STRUCTURE = 'STRUCTURE',
  OFFERING = 'OFFERING',
  STRATEGY = 'STRATEGY',
  GOVERNANCE = 'GOVERNANCE',
  OPERATIONS = 'OPERATIONS',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  RISK_COMPLIANCE = 'RISK_COMPLIANCE',
  EXTERNAL_MARKET = 'EXTERNAL_MARKET'
}
