export enum RelationshipCategory {
  STRUCTURAL = 'STRUCTURAL',
  BEHAVIORAL = 'BEHAVIORAL',
  FUNCTIONAL = 'FUNCTIONAL',
  STRATEGIC = 'STRATEGIC',
  FINANCIAL = 'FINANCIAL',
  GOVERNANCE = 'GOVERNANCE',
  OPERATIONAL = 'OPERATIONAL',
  DEPENDENCY = 'DEPENDENCY'
}
