export enum RelationshipType {
  OWNS = 'OWNS',
  USES = 'USES',
  SUPPORTS = 'SUPPORTS',
  DEPENDS_ON = 'DEPENDS_ON',
  IMPLEMENTS = 'IMPLEMENTS',
  REPORTS_TO = 'REPORTS_TO',
  GOVERNS = 'GOVERNS',
  FUNDS = 'FUNDS',
  ENABLES = 'ENABLES',
  DELIVERS = 'DELIVERS',
  MEMBER_OF = 'MEMBER_OF',
  RELATED_TO = 'RELATED_TO',
  AFFECTS = 'AFFECTS'
}
